### DISCUSSION TITLE
winget configure and its place within the product

### DISCUSSION THREAD

**Discussion by MeikTranel** [microsoft/winget-cli#3346] [General]
How does `winget configure` fit into the overall product - i just started authoring some configurations and i honestly have no idea what to think. Is the DSC YAML supposed to be the new home for DSC configs, will it stop at being a lightweight DSC intro?

I've had some pain points trying to do some basic dev machine setup here - most of these fail because some basic dsc resources fail or are just not supported from PSCore.

```yaml
# Enable WSL
   - resource: PSDscResources/WindowsOptionalFeature
     directives:
       description: Enable WSL
     settings:
       Name: Microsoft-Windows-Subsystem-Linux
# Setup Git
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: git
    directives:
      description: Install GIT
      allowPrerelease: true
    settings:
      id: git.git
      source: winget

  - resource: File
    directives:
      description: Use gitconfig from repo
    dependsOn:
      - git
    settings:
      SourcePath: ${WinGetConfigRoot}\.gitconfig
      DestinationPath: $env:UserProfile\.gitconfig
```
![image](https://github.com/microsoft/winget-cli/assets/6466560/e74189ce-901a-4e0c-a167-2579f991f552)

WSL Enabling fails because apparently `winget configure` runs `pwsh.exe` which cannot run PS Code regarding windows optional feature management.

Copying files using the `File` resource fails because apparently it needs windows management dlls which cannot be loaded in ps core also.

So i tried writing the copying via `Script` resource - lo and behold - it is painful:

```yaml
  - resource: Script
    directives:
      description: Use .gitconfig from repo
    settings:
      GetScript: Write-Host 'Still absolutely no idea what this is for'
      SetScript: Copy-Item -Path ${WinGetConfigRoot}\.gitconfig -Destination "$env:UserProfile\.testgitconfig"
      TestScript: (Test-Path -Path "$env:UserProfile\.testgitconfig") -and (compare-object (get-content ${WinGetConfigRoot}\.gitconfig) (get-content "$env:UserProfile\.testgitconfig"))
```

What im seeing is there seems to be no way to have variables except some well known variables like `${WinGetConfigRoot}` that are documented nowhere so i have do guess that ${UserProfile} isnt available.

Alot of this feels like a super reduced subset of DSC in itself which seems to crumble once it goes one inch beyond winget package install - so why are we introducing a new DSL when there is powershell for DSC and a PS-based DSL already. All samples provided in the various repos updated during build are basically winget and VSPackage only - why not import a app id / source moniker combo list from a file and call it a day?

Where does microsoft see this feature in the future?
