### DISCUSSION TITLE
Examples of using Script (or other) "in-the-box" DSC Resource with Winget Configure

### DISCUSSION THREAD

**Discussion by codekaizen** [microsoft/winget-cli#3764] [Configuration]
I've use the winget configure YAML file samples to build a script that installs various tools on a developer machine. I want to use the Script DSC Resource but there are no examples of how to do this. 

The properties that a given DSC resource needs could be linked to or examples given. Otherwise, this feature is very hard to understand and make use of.

**Comment by denelon** [comment]
This is not the best example, and we are working on documentation.

Notably, when a script resource is used, the get and test methods should be idempotent and perform a "no-op" if the thing to be configured is in the desired state.

This comment has an example of using the PSDResources/Script DSC Resource:
https://github.com/microsoft/winget-cli/issues/3887#issuecomment-1810861812

**Reply by Trenly** [reply]
There is also an example of the Script resource in the [YamlCreate configuration](https://github.com/microsoft/winget-pkgs/blob/master/.configurations/YamlCreate.dsc.yaml) over at winget-pkgs.

The [Script DSC Resource](https://learn.microsoft.com/en-us/powershell/dsc/reference/resources/windows/scriptresource?view=dsc-1.1) has some decent documentation. The biggest things to note are -
* GetScript doesn’t do much, but if you do return a value it needs to be a hashtable containing a `Result` key with a string value
* TestScript needs to return true or false indicating whether the system is in the desired state
* SetScript sets the system to the desired state, and doesn’t need to have a return value

**Comment by denelon** [comment]
@codekaizen,
Could you share what you're trying to do with the script resource? I'd like to understand the gap and see if there is a resource that could already accomplish what you need, and to see if we should build something to better address that gap.

**Reply by harrhp** [reply]
here some of the scenarios i use script resource for
1. set file content from another file. gitconifg, pwsh profile, windows terminal settings
```
- resource: xPSDesiredStateConfiguration/xScript
      directives:
        description: configure git
        allowPrerelease: true
      settings:
        GetScript: "state"
        TestScript: $false
        SetScript: |
          Get-Content (Join-Path ${WingetConfigRoot} "../../files/.gitconfig" -Resolve)
          | Set-Content -Path "~/.gitconfig"
```

2. change content of a file
```
- resource: xPSDesiredStateConfiguration/xScript
      directives:
        description: remove administrators_authorized_keys from sshd congig
        allowPrerelease: true
      settings:
        GetScript: "state"
        TestScript: $false
        SetScript: |
          $path = "C:\ProgramData\ssh\sshd_config";
          $pattern = '(Match Group administrators(?:\r?\n.*)*?\r?\n)(\s+AuthorizedKeysFile .*)'
          $fileContent = Get-Content $path -Raw
          $newContent = $fileContent -replace $pattern | foreach { $_.TrimEnd() }
          Set-Content $path $newContent;
```

**Reply by ColoredCarrot** [reply]
Another use case: We're using `Script` to configure [`ccache`](https://ccache.dev/):

```yaml
- resource: Microsoft.WinGet.DSC/WinGetPackage
  id: installCCache
  directives:
    allowPrerelease: true
  settings:
    id: Ccache.Ccache
    useLatest: true
    source: winget

- resource: Script
  id: configureCCache
  dependsOn: [ installCCache ]
  settings:
    getScript: "% 'no-op'"
    setScript: "ccache --set-config sloppiness=time_macros"
    testScript: "(ccache --get-config sloppiness) -eq 'time_macros'"
```

In this case, the `ccache` CLI already guarantees idempotency/etc., so writing a custom DSC resource seems overkill.

Side note: Is it intended that `winget configure test` runs the `testScript` even when `ccache` is not installed, leading to a "command not found" error? I would have thought that `dependsOn` was for just this case.
