### DISCUSSION TITLE
How do we support VS Code Insiders in winget?

### DISCUSSION THREAD

**Discussion by Tyriar** [microsoft/winget-cli#383] [Q&A] [answered]
Related: https://github.com/microsoft/winget-pkgs/issues/277

`code-insiders` is published approximately daily, while we could automate a PR for stable I don't think it makes sense to do this for Insiders. We have a web endpoint that points to the latest version, can we just not include a `Version` in the manifest?

@KevinLaMS

**Comment by KevinLaMS** [comment]
Hey Tyriar:
I think what you are asking for is channel support?
I will be happy to sync with you on this:
https://github.com/microsoft/winget-cli/issues/147

**Comment by Tyriar** [comment]
@KevinLaMS no not channels, we ship as 2 separate binaries such that you can install side-by-side. I'm envisioning what we do with the Linux packages where there is a separate app `code-insiders` that is defined separately to `code`.

Insiders is published to a lot, and we also need to be able to delete versions, this is all handled by the built-in updater. Another way of saying what I'm after is whether it's possible to create a `https://github.com/microsoft/winget-pkgs/blob/master/manifests/Microsoft/VisualStudioCodeInsiders/latest.yaml` where `Version` is either unset or set to something like `latest`, and then point it to our endpoint that downloads the latest insiders.

**Comment by Tyriar** [comment]
We also have an "exploration" build which is available on other platform package managers too:

http://packages.microsoft.com/repos/vscode/pool/main/c/
http://packages.microsoft.com/yumrepos/vscode/
https://snapcraft.io/code
https://snapcraft.io/code-insiders

**Comment by RobertBernstein** [comment]
So before I saw this issue and microsoft/winget-pkgs#327 , I tried creating my own manifest file for VS Code Insiders (using .\YamlCreate.ps1) and was going to submit a PR.  However, while the manifest file passed validation, the installation failed using `winget.exe install -m .\1.46.0.yaml`. I got the following dialog box:

![image](https://user-images.githubusercontent.com/845559/82393081-75d26400-9a13-11ea-93ac-3ba55fbf38f4.png)

Here is my manifest file:

```yaml
Id: Microsoft.VisualStudioCodeInsiders.UserInstaller
Version: 1.46.0
Name: Visual Studio Code Insiders (User)
Publisher: Microsoft Corporation
License: Copyright (c) Microsoft Corporation
AppMoniker: vscodeinsiders
Tags: vscode, insiders, editor
Description: The Visual Studio Code Insiders build is a code editor for early adopters that is optimized for building and debugging modern web and cloud applications.
Homepage: https://code.visualstudio.com/insiders/
Installers:
  - Arch: x64
    Url: https://az764295.vo.msecnd.net/insider/da3bf754c3c0eabda1dc80ed9d627679ee560697/VSCodeUserSetup-x64-1.46.0-insider.exe
    Sha256: 21D54D6B34B63F1FB41B0D21816E9B1CF1A5E1578AF810A805D3CE2086B2E773
    InstallerType: Inno
```

There were no logs files that I could find in the %temp% directory. I tried specifying -o .\log.txt, but that also produced no log file. How can I understand why it failed? Should I open this as a separate issue?

Thanks in advance.

Rob
