### DISCUSSION TITLE
Install VSCode extensions using winget configure file

### DISCUSSION THREAD

**Discussion by HeinvR** [microsoft/winget-cli#3958] [Q&A] [answered]
Is it possible to install VSCode extensions using a YAML configure file? 

ATM i'm installing my VSCode extensions using PS commands after running Winget configure. It would be great if i can somehow manage to put these in my YAML config file. Then i'm able to setup my whole dev environment using Winget configure only.

**PS commands i currently use:**
code --install-extension ms-azuretools.vscode-bicep --force
code --install-extension ms-vscode.PowerShell --force
code --install-extension ms-vscode.azure-account --force

**vscode YAML config:**
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        module: Microsoft.WinGet.DSC
        description: 'Install Microsoft Visual Studio Code'
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

It would be great if someone can point me to the right direction

**Comment by Trenly** [comment, marked as answer]
The trick is finding the right DSC resource. Searching the PowerShell Gallery, I was able to find the [vscode](https://www.powershellgallery.com/packages/vscode/1.0) package. Once you import the module, you can use `$(Get-DscResource).Where({$_.ModuleName -eq 'vscode'})` to see all the resources the module provides as well as what properties they accept. 

Here's an example -
```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/microsoft/winget-cli#building-the-client
properties:
  resources:
    - resource: vscode/VSCodeExtension
      directives:
        description: Install YAML Extension
        allowPrerelease: true
      settings:
        Name: redhat.vscode-yaml
        Ensure: Present
  configurationVersion: 0.2.0
```
