### DISCUSSION TITLE
Windows Package Manager 1.10.30-preview

### DISCUSSION THREAD

**Discussion by ryfu-msft** [microsoft/winget-cli#4945] [Releases]
This is the first development build after the Windows Package Manager 1.9 build for Windows 10(1809+) and Windows 11.
This build will be released to Windows Insider Dev builds and Windows Package Manager Insiders.

This release includes the ability to enable experimental features unless blocked by Group Policy Objects (GPO)

---

Sixel support is here to display icons and a new progress visualization. To try out this new feature, you must be using a terminal that supports sixels, such as the [latest Windows Terminal Preview build.](https://github.com/microsoft/terminal/releases/tag/v1.22.2362.0) To enable this feature, include the following snipping in your settings file:

```json
{
  "$schema": "https://aka.ms/winget-settings.schema.json",
  "visual": {
    "enableSixels": true,
    "progressBar": "sixel"
  }
}
```
---

WinGet Configuration files with DSC Resources requiring elevation can now be handled more gracefully. The "Configure Self Elevation" experimental feature can be enabled with the following snippet in your settings file:

```json
{
  "$schema": "https://aka.ms/winget-settings.schema.json",
  "experimentalFeatures": {
    "configureSelfElevate": true
  }
}
```

Use "securityContext: elevated" under "directives:" for any resources requiring administrator. WinGet will trigger a single User Account Control (UAC) prompt when the configuration is run under user context. Resources requiring elevation are run elevated, and the rest are run in user context. The following example shows how the [.NET Tutorial - Hello World in 5 minutes](https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/intro) will be updated to provide a better user experience.

```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: install-dotnet8-SDK
      directives:
        description: Install .NET 8 SDK
        securityContext: elevated
      settings:
        id: Microsoft.DotNet.SDK.8
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: install-vs-code
      directives:
        description: Install Visual Studio Code
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.VSCode.DSC/VSCodeExtension
      id: install-csharp-dev-kit
      dependsOn:
        - install-vs-code
      directives:
        description: Install C# Dev Kit
        allowPrerelease: true
      settings:
        name: ms-dotnettools.csdevkit
        exist: true
  configurationVersion: 0.2.0
```

## What's Changed
* Make adding overlapping ARP range a hard error by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/4870
* Update minor version by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/4874
* Update package with CVEs by @florelis in https://github.com/microsoft/winget-cli/pull/4881
* Add ADMX policies for security features in App Installer by @florelis in https://github.com/microsoft/winget-cli/pull/4726
* Consume all input during extract sequence by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/4882
* Change meaning of AddOrUpdate return bool by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/4885
* Fix for Source Argument Validation in SourceWorkflow for Default Source Type by @Madhusudhan-MSFT in https://github.com/microsoft/winget-cli/pull/4891
* add latest localized strings by @ryfu-msft in https://github.com/microsoft/winget-cli/pull/4892
* Bring back WinGetUtil nuspec for dev development by @msftrubengu in https://github.com/microsoft/winget-cli/pull/4884
* Add support for 1.9 manifest in rest source parsing and winget utils interop by @yao-msft in https://github.com/microsoft/winget-cli/pull/4906
* WinGet Source COM Api by @Madhusudhan-MSFT in https://github.com/microsoft/winget-cli/pull/4813
* Add experimental feature for font list command by @ryfu-msft in https://github.com/microsoft/winget-cli/pull/4886
* Fix Microsoft Store's App Installer URL by @mdanish-kh in https://github.com/microsoft/winget-cli/pull/4925
* Fix Repair-WinGetPackageManager cmdlet by retrieving dependencies from GitHub assets by @ryfu-msft in https://github.com/microsoft/winget-cli/pull/4923
* Remove attribute in DSC by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/4932
* Add msstore productId to export manifest and to wingetutil interop manifest object by @yao-msft in https://github.com/microsoft/winget-cli/pull/4934

**Full Changelog**: https://github.com/microsoft/winget-cli/compare/v1.9.25180...v1.10.30-preview

<hr /><em>This discussion was created from the release <a href='https://github.com/microsoft/winget-cli/releases/tag/v1.10.30-preview'>Windows Package Manager 1.10.30-preview</a>.</em>
