### DISCUSSION TITLE
Is it possible to use xPSDesiredStateConfiguration/xRegistry resource in winget configuration?

### DISCUSSION THREAD

**Discussion by tristanbarcelon** [microsoft/winget-cli#4971] [Q&A]
I'm trying to create a winget configuration which would perform the following steps in sequence on Windows:
- assert that Windows is 10.0.20348 or later

install the following resources:
- add/update value of HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled to DWORD of 1
- install winget package Microsoft.VisualStudioCode
- install winget package Git.Git
- install winget package GitTools.GitVersion
- install winget package OpenJS.NodeJS.LTS
etc...

has anyone tried to use xRegistry resource from xPSDesiredStateConfiguration to set LongPathsEnabled to 1 from a winget configuration file successfully? How would you incorporate it in the resource settings?

**Comment by tristanbarcelon** [comment]
Here's my yaml and it works:

```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify Windows Server version is 2022 or higher
        allowPrerelease: true
      settings:
        MinVersion: '10.0.20348' # 2025 is 10.0.26100
  resources:
    - resource: SChannelDSC/SChannelSettings
      directives:
        description: Enable TLS 1.2 and set HttpDefaultSecureProtocols to TLS 1.2
        allowPrerelease: false
      settings:
        IsSingleInstance: 'Yes'
        TLS12State: 'Enabled'
        WinHttpDefaultSecureProtocols: ['TLS1.2']
    - resource: xPSDesiredStateConfiguration/xRegistry
      id: RegLongPaths
      directives:
        description: Ensure LongFilePaths registry key is present and set to 1
        allowPrerelease: false
      settings:
        Key: HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem
        Ensure: 'Present'
        ValueName: LongPathsEnabled
        ValueType: 'Dword'
        ValueData: '1'
        Force: true
    - resource: ComputerManagementDsc/PowerPlan
      directives:
        description: Ensure power plan is set to High Performance
        allowPrerelease: false
      settings:
        IsSingleInstance: 'Yes'
        Name: 'High Performance'
    - resource: ComputerManagementDsc/RemoteDesktopAdmin
      directives:
        description: Ensure remote desktop is enabled
        allowPrerelease: false
      settings:
        IsSingleInstance: 'Yes'
        Ensure: 'Present'
        UserAuthentication: 'Secure'
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      dependsOn:
        - RegLongPaths
      directives:
        description: Install Microsoft.VisualStudioCode
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: notepad++
      dependsOn:
        - vscode
      directives:
        description: Install NotePad++.NotePad++
        allowPrerelease: false
      settings:
        id: NotePad++.NotePad++
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: winmerge
      dependsOn:
        - notepad++
      directives:
        description: Install WinMerge.WinMerge
        allowPrerelease: false
      settings:
        id: WinMerge.WinMerge
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: 7zip
      dependsOn:
        - winmerge
      directives:
        description: Install 7zip.7zip
        allowPrerelease: false
      settings:
        id: 7zip.7zip
        source: winget
        uselatest: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: git
      dependsOn:
        - 7zip
      directives:
        description: Install Git.Git
        allowPrerelease: false
      settings:
        id: Git.Git
        source: winget
        Ensure: 'Present'
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nodejs
      dependsOn:
        - git
      directives:
        description: Install OpenJS.NodeJS.LTS
        allowPrerelease: false
      settings:
        id: OpenJS.NodeJS.LTS
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: googlechrome
      dependsOn:
        - nodejs
      directives:
        description: Install Google.Chrome
        allowPrerelease: false
      settings:
        id: Google.Chrome
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: awscli
      dependsOn:
        - googlechrome
      directives:
        description: Install Amazon.AwsCli
        allowPrerelease: false
      settings:
        id: Amazon.AwsCli
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: azurecli
      dependsOn:
        - awscli
      directives:
        description: Install Microsoft.AzureCLI
        allowPrerelease: false
      settings:
        id: Microsoft.AzureCli
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: terraform
      dependsOn:
        - azurecli
      directives:
        description: Install Hashicorp.Terraform
        allowPrerelease: false
      settings:
        id: Hashicorp.Terraform
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: kubectl
      dependsOn:
        - azurecli
      directives:
        description: Install Kubernetes.kubectl
        allowPrerelease: false
      settings:
        id: Kubernetes.kubectl
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: helm
      dependsOn:
        - azurecli
      directives:
        description: Install Helm.Helm
        allowPrerelease: false
      settings:
        id: Helm.Helm
        source: winget
  configurationVersion: 0.2.0
```
<img width="209" alt="image" src="https://github.com/user-attachments/assets/ef8cb56d-7dea-4791-810a-cc1111984bbd">
