### DISCUSSION TITLE
Is it possible to use environment variable on configuration files?

### DISCUSSION THREAD

**Discussion by ariellourenco** [microsoft/winget-cli#5176] [Configuration]
Hi there,

I am trying to use WinGet configuration file to create a new Virtual Hard Disk to store my Dev Drive. However, I am struggling to follow the Microsoft recommendation for VHD Dev Drives which recommend use a per-user directory path location to store your Dev Drive to avoid any unintentional sharing. 

So far, I got the configuration file below, which works just fine. However, I would like to  update the `FilePath:` property to use the user profile environment variable. 

```yaml
# ymal-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      id: OsVersion
      directives:
        description: Minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22621.2338"
  resources:
    - resource: VirtualHardDrive
      directives:
        description: Create a new Virtual Hard Drive
        module: StorageDsc
        allowPrerelease: true
      settings:
        FilePath: 'C:\DevDrives\Zero.vhdx'
        DiskSize: 50Gb
        DiskFormat: 'Vhdx'
        DiskType: 'Dynamic'
        Ensure: 'Present'
```

Any idea if that is possible? And if so, how to achieve it? So far, I have tried a few variants such as `%USERPROFILE%` and `$env:UserProfile`
