### DISCUSSION TITLE
Install-Modules with WinGet Configuration file

### DISCUSSION THREAD

**Discussion by ariellourenco** [microsoft/winget-cli#5271] [PowerShell]
Hi there,

I have a simple `configuration.dsc.yaml` file that attempts to setup the Windows PowerShell on a brand new machine. The script should update the PowerShellGet module to the lasted version and install a few other modules. Nothing fancy really! 

However, this simple task does not work. It seems like each resource block in my configuration file creates a dedicated PowerShell session and, therefore, run commands on Windows PowerShell need to be done as follow:

```powershell
$windowsPSFolder = "$env:SystemRoot\System32\WindowsPowershell\v1.0"
$windowsPSExe      = "$windowsPSFolder\powershell.exe"

$powerShellGetVersion = & $windowsPSExe -Command "Get-Module -ListAvailable -Name PowerShellGet | Select-Object -First 1 -ExpandProperty Version"

Write-Debug "PowerShellGet version $powerShellGetVersion"

if ($powerShellGetVersion -lt [version]"1.6.0") {
  # Windows PowerShell 5.1 comes with version 1.0.0.1 of the PowerShellGet and PackageManagement preinstalled.
  # However, this version of PowerShellGet has a limited features and must be updated to work with
  # the PowerShell Gallery.
  throw "The installed PowerShellGet version ($powerShellGetVersion) is less than the required version 1.6.0."
}

Write-Verbose -Message "🧩 Installing PowerShell modules." -Verbose

& $windowsPSExe -Command "Install-Module -Name PSReadLine -Force"
```

## configuration.dsc.yaml

```yaml
# ymal-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      id: OsVersion
      directives:
        description: Minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22621.2338"
  resources:
    - resource: PSDscResources/Script
      directives:
        description: Setup Windows PowerShell
        allowPrerelease: true
      settings:
        GetScript: return $false
        TestScript: return $false
        SetScript: |
          $profile                = 'D:\dotfiles\windows\Profile.ps1'
          $windowsPSProfileFolder = "$env:USERPROFILE\Documents\WindowsPowerShell"
          $windowsPSFolder        = "$env:SystemRoot\System32\WindowsPowershell\v1.0"
          $windowsPSExe           = "$windowsPSFolder\powershell.exe"

          $powerShellGetVersion = & $windowsPSExe -Command "Get-Module -ListAvailable -Name PowerShellGet | Select-Object -First 1 -ExpandProperty Version"

          Write-Debug "PowerShellGet version $powerShellGetVersion"

          if ($powerShellGetVersion -lt [version]"1.6.0") {
            # Windows PowerShell 5.1 comes with version 1.0.0.1 of the PowerShellGet and PackageManagement preinstalled.
            # However, this version of PowerShellGet has a limited features and must be updated to work with
            # the PowerShell Gallery.
            throw "The installed PowerShellGet version ($powerShellGetVersion) is less than the required version 1.6.0."
          }

          Write-Verbose -Message "🧩 Installing PowerShell modules." -Verbose

          & $windowsPSExe -Command "Install-Module -Name PSReadLine -Force"
          & $windowsPSExe -Command "Install-Module -Name Terminal-Icons -Scope CurrentUser -Force"

          Write-Verbose -Message "📄 Copying Profile.ps1 to $windowsPSProfileFolder directory." -Verbose

          Copy-Item -Path $profile -Destination $windowsPSProfileFolder -Force
```

But unfortunately this code does not work! It always gets into the `if` clause even though when the PowerShellGet module is greater than the specified version. Any idea about what is going on here?
