### DISCUSSION TITLE
Windows Package Manager 1.11.320-preview

### DISCUSSION THREAD

**Discussion by florelis** [microsoft/winget-cli#5457] [Releases]
This is a preview build of WinGet for those interested in trying out upcoming features and fixes. While it has had some use and should be free of major issues, it may have bugs or usability problems. If you find any, please help us out by [filing an issue](https://github.com/microsoft/winget-cli/issues).

## New in v1.11
* Dropped support for running on 32-bit ARM

## Experimental Features
* Experimental support for DSC v3 processing
* Experimental support for Configuration Export
* Experimental support for Fonts

---
### Experimental support for DSC v3 processing
The following snippet enables experimental support for [Microsoft Desired State Configuration](https://learn.microsoft.com/powershell/dsc/overview?view=dsc-3.0). 
```JSON
{
  "$schema" "https://aka.ms/winget-settings.schema.json",
  "experimentalFeatures": {
    "dsc3": true
  }
}
```

---
### Experimental support for Configuration Export
The following snippet enables experimental support for exporting the configuration of the current device. This includes Windows Settings, packages from configured WinGet sources, and  package settings from DSC v3 enabled packages.
```JSON
{
  "$schema" "https://aka.ms/winget-settings.schema.json",
  "experimentalFeatures": {
    "configureExport": true
  }
}

```

---
### Experimental support for Fonts
The following snippet enables experimental support for fonts via `winget settings`. The `winget font list` command will list installed font families and the number of installed font faces.
```JSON
{
  "$schema" "https://aka.ms/winget-settings.schema.json",
  "experimentalFeatures": {
    "fonts": true
  }
}

```

## What's Changed
* troubleshooting source error by @denelon in https://github.com/microsoft/winget-cli/pull/5370
* Fixes for pipeline stability by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/5359
* Fix it twice by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/5381
* Handle not finding metadata by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/5350
* DSC v3 adapter support by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/5302
* Lower Schema Header Validation to include 1.7+ manifests by @Trenly in https://github.com/microsoft/winget-cli/pull/5330
* Update OneFuzzConfig.json by @florelis in https://github.com/microsoft/winget-cli/pull/5380
* Better DefaultInstallVersion by @yao-msft in https://github.com/microsoft/winget-cli/pull/5389
* Remove most checked-in dependency libraries by @florelis in https://github.com/microsoft/winget-cli/pull/5390
* Add api to find unit processors based on search path by @yao-msft in https://github.com/microsoft/winget-cli/pull/5386
* Remove clones of transitive dependencies available from vcpkg by @florelis in https://github.com/microsoft/winget-cli/pull/5399
* Update curl to 1.12.1 by @florelis in https://github.com/microsoft/winget-cli/pull/5404
* Disable assembly info override by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/5405
* Dscv3 package resource by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/5395
* Dscv3 source resource by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/5418
* Enable NuGet Central Package Management by @florelis in https://github.com/microsoft/winget-cli/pull/5420
* Ensure all vcpkgs use our custom triplets by @florelis in https://github.com/microsoft/winget-cli/pull/5423
* Update sample projects to 1.10.340 by @florelis in https://github.com/microsoft/winget-cli/pull/5427
* Added dscv3 user-settings resource by @AmelBawa-msft in https://github.com/microsoft/winget-cli/pull/5421
* Fix debug build with vcpkg by @yao-msft in https://github.com/microsoft/winget-cli/pull/5430
* Add support for exporting package related DSC v3 resources and some predefined resources in configure export all  by @yao-msft in https://github.com/microsoft/winget-cli/pull/5428
* Fix arm64-release-static vcpkg triplet by @florelis in https://github.com/microsoft/winget-cli/pull/5431
* Remove purelib.vcxproj by @florelis in https://github.com/microsoft/winget-cli/pull/5429
* Create a vcpkg overlay for cpprestsdk and libyaml by @florelis in https://github.com/microsoft/winget-cli/pull/5424
* Allow preview dsc while experimental by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/5434
* Place DSCv3 resource manifests in the package by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/5433
* Install dsc v3 package if not found when processing dsc v3 configuration file by @yao-msft in https://github.com/microsoft/winget-cli/pull/5437
* Use Microsoft.Windows.Settings in configure export all by @yao-msft in https://github.com/microsoft/winget-cli/pull/5441
* Make partial the default for user-settings-file by @AmelBawa-msft in https://github.com/microsoft/winget-cli/pull/5442
* Ignore comments when writing JSON output in WinGet DSC v3 resources by @AmelBawa-msft in https://github.com/microsoft/winget-cli/pull/5445
* Attempt to use DSCv3 resources even if they were not found by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/5443
* Elevated for exported Microsoft.Windows.Settings by @yao-msft in https://github.com/microsoft/winget-cli/pull/5444
* Use Microsoft.Windows.Settings module for enabling developer mode by @mdanish-kh in https://github.com/microsoft/winget-cli/pull/5448
* Fix fuzzing job path by @yao-msft in https://github.com/microsoft/winget-cli/pull/5447
* Only forward the verbose property if it has been set by @JohnMcPMS in https://github.com/microsoft/winget-cli/pull/5449

**Full Changelog**: https://github.com/microsoft/winget-cli/compare/v1.11.230-preview...v1.11.320-preview

---

_This discussion was created from the release [Windows Package Manager 1.11.320-preview](https://github.com/microsoft/winget-cli/releases/tag/v1.11.320-preview)._

**Comment by denelon** [comment]
Hey everyone, I had a [couple of presentations at Build](https://build.microsoft.com/speakers/6034a792-83df-4bfb-a625-3cfa9ebb43f5) covering the experimental features for Microsoft Desired State Configuration and WinGet Configuration Export.

This is the version of WinGet I used, but there was some manual setup involved:

Two experimental features (dsc3 and configureExport) need to be enabled.

I was using DSC.exe (the packaged version of the 3.1 preview from the Microsoft Store), and I had to make sure the WinGet resource manifests were available on the path. I covered one way to do this in another [comment](https://github.com/microsoft/winget-cli/issues/3274#issuecomment-2905128478).

If you run `dsc resource list` you should see the WinGet resources present.

**Reply by denelon** [reply]
Demo.winget

```YAML

$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
metadata:
  winget:
    processor: dscv3
resources:
  - name: WindowsSettings
    type: Microsoft.Windows.Settings/WindowsSettings
    metadata:
      allowPrerelease: true
      description: Configure Windows Settings
    properties:
      TaskbarAlignment: Left
      AppColorMode: Dark
      SystemColorMode: Dark
      DeveloperMode: true
  - name: PowerShell
    type: Microsoft.WinGet/Package
    metadata:
      description: PowerShell 7
    properties:
        id: Microsoft.PowerShell
        source: winget     
  - name: PowerToys
    type: Microsoft.WinGet/Package
    metadata:
      description: PowerToys
    properties:
        id: Microsoft.PowerToys
        source: winget     
  - name: WindowsTerminal
    type: Microsoft.WinGet/Package
    metadata:
      description: Windows Terminal
    properties:
        id: Microsoft.WindowsTerminal
        source: winget    

```

**Reply by denelon** [reply]
Reset.winget

```YAML

$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
metadata:
  winget:
    processor: dscv3
resources:
  - name: WindowsSettings
    type: Microsoft.Windows.Settings/WindowsSettings
    metadata:
      allowPrerelease: true
      description: Configure Windows Settings
    properties:
      TaskbarAlignment: Center
      AppColorMode: Light
      SystemColorMode: Light
      # DeveloperMode: false
  - name: PowerShell
    type: Microsoft.WinGet/Package
    metadata:
      description: PowerShell 7
    properties:
        id: Microsoft.PowerShell
        source: winget     
  - name: PowerToys
    type: Microsoft.WinGet/Package
    metadata:
      description: PowerToys
    properties:
        id: Microsoft.PowerToys
        source: winget     
  - name: WindowsTerminal
    type: Microsoft.WinGet/Package
    metadata:
      description: Windows Terminal
    properties:
        id: Microsoft.WindowsTerminal
        source: winget    
```
