### DISCUSSION TITLE
How would a configuration for a fresh, personal Windows 11 install look like?

### DISCUSSION THREAD

**Discussion by totkeks** [microsoft/winget-cli#5462] [Configuration]
Hello community,

I'm currently working on my dotfiles / windows system setup using WinGet configurations.

I started with a simple configuration that installs the PowerShell modules required by my dotfiles, like this:
```yaml
    - resource: PowerShellGet/PSModule
      id: PsIni
      directives:
        description: Install PsIni module from PSGallery
        allowPrerelease: true
      settings:
        Name: PsIni
        Repository: PSGallery
        Ensure: Present
```

Then I stumbled on the execution policy issue, which is `Untrusted` by default.

So, I went ahead and added this configuration block:
```yaml
    - resource: Microsoft.PowerShell.ExecutionPolicy
      settings:
        ExecutionPolicy: Unrestricted
        Scope: User
```

New issue now though. That results in `The configuration unit could not be found`.
After a bit of search and thinking I realized, this needs the new PowerShell Core (7+) to be installed.

The logical next step would now be to install the new PowerShell first in that configuration. But that also doesn't work, because the DSC modules required to install packages also require the new PowerShell.

Is there any way this would be possible with a single configuration file? Or do I have to resort to a PowerShell 5 script, that runs the PowerShell 7 install, and then runs the configuration?
