### DISCUSSION TITLE
Unable to validate multi file manifest

### DISCUSSION THREAD

**Discussion by d3vel0per** [microsoft/winget-cli#991] [Q&A] [answered]
Running `winget validate <manifest>` results in manifest validations error eg.

```
Manifest validation failed.
Manifest Error: The multi file manifest is incomplete. A multi file manifest must contain at least version, installer and defaultLocale manifest. File: Azul.Zulu.16.yaml
```

for the below mentioned manifests. Not really sure what I missed. Any guidance will be helpful.

**Azul.Zulu.16.yaml**
```yaml
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json
PackageIdentifier: Azul.Zulu.16
PackageVersion: 16.0.1
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0

```

**Azul.Zulu.16.installer.yaml**
```yaml
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Azul.Zulu.16
PackageVersion: 16.0.1
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerType: msi
    InstallerUrl: https://cdn.azul.com/zulu/bin/zulu16.30.15-ca-jdk16.0.1-win_x64.msi
    InstallerSha256: 146BBF0758172A6D4291F2116F4A2EB40F0D22FF534C65493471FF867378E783
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

```

**Azul.Zulu.16.locale.en-US.yaml**
```yaml
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultlocale.1.0.0.schema.json
PackageIdentifier: Azul.Zulu.16
PackageVersion: 16.0.1
PackageLocale: en-US
Publisher: Azul
PublisherUrl: https://www.azul.com/
Author: Azul
PackageName: Azul Zulu 16
PackageUrl: https://www.azul.com/downloads/
License: GPL-2.0-only WITH Classpath-exception-2.0
LicenseUrl: https://www.azulsystems.com/license/zulu_third_party_licenses.html
ShortDescription: Zulu 16 is a build of OpenJDK 16
Moniker: azulzulu-openjdk-16
Tags:
  - Java
  - Zulu
  - OpenJDK
ManifestType: defaultLocale
ManifestVersion: 1.0.0

```
