### ISSUE TITLE
Winget should support 302 redirect package URLs

### ISSUE THREAD

**Issue by palenshus** [microsoft/winget-cli#1115]
# Brief description of your issue

It seems that winget at some point supported 302 redirect package URLs, for example https://download.qt.io/official_releases/qtcreator/4.15/4.15.0/qt-creator-opensource-windows-x86_64-4.15.0.exe

However, it no longer seems to, possibly as a result of using DO.

# Steps to reproduce

Create singleton.yaml manifest file:

```
PackageIdentifier: TestPublisher.TestApp
PackageVersion: 0.1.2
Installers:
  - Architecture: x64
    InstallerUrl: https://download.qt.io/official_releases/qtcreator/4.15/4.15.0/qt-creator-opensource-windows-x86_64-4.15.0.exe
    InstallerType: exe
    InstallerSha256: ec0d13c102f63b47aeb530386950484974ec1e54f598f1b6591039b26816041c
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
```

    winget install -m singleton.yaml

# Expected behavior

App should download

# Actual behavior

```
Found  [TestPublisher.TestApp]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.qt.io/official_releases/qtcreator/4.15/4.15.0/qt-creator-opensource-windows-x86_64-4.15.0.exe
An unexpected error occurred while executing the command:
0x80190003 : Unexpected redirection status code (3xx).
```

# Environment

Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.985
Package: Microsoft.DesktopAppInstaller v1.11.11451.0
