### ISSUE TITLE
Add MSI UpgradeCode to manifest

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1145]
# MSI Installer UpgradeCode

MSI Installers have an UpgradeCode to help with package upgrades:
[Using an UpgradeCode]https://docs.microsoft.com/en-us/windows/win32/msi/using-an-upgradecode)

**Comment by denelon** [comment]
How about from #1073:

```YAML
ProgramsAndFeaturesEntries:
  - Name: Foo
    Publisher: Contoso
    Version: 1.2.3
    ProductCode: "{AAAAA-AAAAA-AAAAA-AAAAA-AAAAA}"
    UpgradeCode: "{ABAAA-ABAAA-ABAAA-ABAAA-ABAAA}"
  - Name: FooService
    Publisher: Contoso
    Version: 2.3.4
    ProductCode: "{BBBBB-BBBBB-BBBBB-BBBBB-BBBBB}"
    UpgradeCode: "{BCBBB-BCBBB-BCBBB-BCBBB-BCBBB}"
 ```
