### ISSUE TITLE
Add Markets to manifest

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1241]
# Description of the new feature/enhancement

The new store source we are working on requires information regarding the market a given user is in. We need to extend the manifest to we can support behaviors related to markets.

This would be optional, and a manifest could specify either an allow list, or a deny list. 

# Proposed technical implementation details (optional)

Markets will have an "Allow" list and a "Exclusion" list.
 
If the client receives both lists and any individual market is in both lists the client will not proceed.
&nbsp;And the client will inform the user the manifest is invalid due to markets.
 
If the client receives either (but only one list) the client will only evaluate based on the list it received
If we receive an allow list:
&nbsp;If the client is in the market included in the allow list, then the install will proceed.
&nbsp;If the client is not in the market included in the allow list then the install will not proceed.
&nbsp;&nbsp;And the client will inform the user that the package is not allowed in their market.

If we receive an Exclusion list:
&nbsp;If the client is in the market included in the exclusion list, then the install will not proceed.
&nbsp;&nbsp;And the client will inform the user that the package is not allowed in their market.
&nbsp;If the client is not in the market included in the exclusion list, then the install will proceed.
		 
If the client receives both an allow list and an exclusion list the client will behave as though it only received an allow list.

```YAML
Installers:
  - InstallerType: exe
    InstallerArchitecture: x64
    InstallerSHA256: 12341234123412341234123412341234123412341234
    InstallerURL: https://www.contoso.com/awesomeapp/1.0.0/awesomeapp.x64.exe
    Markets:
      AllowedMarkets:
       - DE
      ExcludedMarkets:
       - US
```
