### ISSUE TITLE
Complex installers

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1242]
# Description of the new feature/enhancement

As we get closer to supporting .zip and standalone .exe installers, we need some additional mechanisms to identify a few different scenarios. These include what kind of an installer is inside of .zip files. It also includes scenarios where a package is distributed with a .exe installer, but it also contains an .msi installer (PowerToys). 

# Proposed technical implementation details (optional)

We would add a new node to the Installers called "NestedInstallerType".

This example would help fix the upgrade scenario related to PowerToys:
```YAML
Installers:
  - InstallerType: exe
    NestedInstallerType: msi
    InstallerArchitecture: x64
    InstallerSHA256: 12341234123412341234123412341234123412341234
    InstallerURL: https://www.contoso.com/awesomeapp/1.0.0/awesomeapp.x64.exe
```

This example is for a nullsoft installer distributed inside of a .zip file, but this could also be .exe, inno, wix, etc.
```YAML
Installers:
  - InstallerType: zip
    NestedInstallerType: nullsoft
    InstallerArchitecture: x64
    InstallerSHA256: 12341234123412341234123412341234123412341234
    InstallerURL: https://www.contoso.com/awesomeapp/1.0.0/awesomeapp.x64.zip
```

This example is for a standalone / portable executable (these are not yet supported) inside of a .zip file.

```YAML
Installers:
  - InstallerType: zip
    NestedInstallerType: standalone
    InstallerArchitecture: x64
    InstallerSHA256: 12341234123412341234123412341234123412341234
    InstallerURL: https://www.contoso.com/awesomeapp/1.0.0/awesomeapp.x64.zip
```
