### ISSUE TITLE
Add the ability to identify unsupported arguments

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1277]
# Description of the new feature/enhancement

Some installers don't support certain arguments like "--location".
See https://github.com/microsoft/winget-pkgs/issues/20228

Others may not support "--log"

# Proposed technical implementation details (optional)

Enhance the schema and the client to inform users when these are known conditions:
"--location"
"--log"

>Note: we may update the description of this issue to identify other scenarios

```YAML
Installers:
  - InstallerType: exe
    InstallerArchitecture: x64
    InstallerSHA256: 12341234123412341234123412341234123412341234
    InstallerURL: https://www.contoso.com/awesomeapp/1.0.0/awesomeapp.x64.exe
    UnsupportedArguments:
      - Location
      - Log
```
