### ISSUE TITLE
Expected return codes

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1278]
# Description of the new feature/enhancement

Some .exe installers provide return error codes for known reasons on install. These aren't exactly the same as "SuccessCodes" because the install didn't complete, but they aren't necessarily catastrophic failures either.

We would like to be able to have standard known error messages that can be easily understood and localized for these installers.

# Proposed technical implementation details (optional)

The Windows Package Manager would have an enumeration of responses to be localized for mapping to specific return codes from installers.

For example some packages return error codes indicating the program is in use and should be exited before install.

OBS Studio returns "5" when the package is already running.

```YAML
Installers:
  - InstallerType: exe
    InstallerArchitecture: x64
    InstallerSHA256: 12341234123412341234123412341234123412341234
    InstallerURL: https://www.contoso.com/awesomeapp/1.0.0/awesomeapp.x64.exe
    EpectedReturnCodes:
      - InstallerReturnCode: 5
        ReturnResponse: PACKAGE_IN_USE
```
