### ISSUE TITLE
PreInstall / PostInstall commands

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#1279]
# Description of the new feature/enhancement
As mentioned in #1278 some installers have error codes for specific circumstances. Having the ability to execute one or two commands could make the users experience more seamless. Additionally, some packages such as f.lux which do not [provide a version number](https://github.com/microsoft/winget-pkgs/issues/16003) could be modified with the command as a temporary workaround for poor development. 

# Proposed technical implementation details (optional)
The Windows Package Manager would have an enumeration of commands to be run before or after the installation or upgrade of a package. These could be enabled by default through a configuration option or with switches. If not specifically enabled, or not required for a package, the CLI could confirm with the user or default to not running the commands. 

Example of switches:
```powershell
winget install package -extended # Runs the PreInstall and PostInstall commands
winget install package -native # Does not run the PreInstall and PostInstall commands
```
Example of manifest
```yaml
Installers:
  - InstallerType: exe
    InstallerArchitecture: x64
    InstallerSHA256: 12341234123412341234123412341234123412341234
    InstallerURL: https://www.contoso.com/awesomeapp/1.0.0/awesomeapp.x64.exe
    Commands:
      - RunOn: [Install, Upgrade, Always]
        Run: [Before, After]
        Command: "taskkill /f /im awesomeapp.exe"
        Description: "This command ensures that Awesome App is not running before the installation"
        Required: true
```

Precautions would have to be taken in the Azure Pipelines for [winget-pkgs](https://github.com/microsoft/winget-pkgs) to ensure that no malicious code is executed.
