### ISSUE TITLE
Add a key for "Requires Elevation" to the manifest schema

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#1284]
# Description of the new feature/enhancement

Some packages require elevation to install.  The Windows Package Manager could provide settings and or arguments to filter results requiring elevation. Some users may not have the ability to elevate, and this could help eliminate a bad experience for them.

# Proposed technical implementation details (optional)

Optional key "RequiresElevation". The default behavior when the key is not present is to treat it as true.

```YAML
Installers:
  - InstallerType: exe
    InstallerArchitecture: x64
    InstallerSHA256: 12341234123412341234123412341234123412341234
    InstallerURL: https://www.contoso.com/awesomeapp/1.0.0/awesomeapp.x64.exe
    RequireElevation: true
```
Edit:

We found examples of packages that do not work with elevation. This schema implementation was extended:
https://github.com/microsoft/winget-cli/blob/5a97e26ba3efb6b1f0d5997ec9de7d16b8fa52b9/schemas/JSON/manifests/v1.1.0/manifest.installer.1.1.0.json#L427-L435

Related To:
* #1537
* microsoft/winget-pkgs/issues/29148
