### ISSUE TITLE
ReleaseDate is not validated as a date.

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-cli#1725]
### Brief description of your issue

In schema v1.1, the `ReleaseDate` field was added, and it's using the [proper JSON Schema ](https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times) syntax to signify it is a date. However, `winget validate` does not check whether the value is a date, instead just verifying it is a string.

I believe this is because Valijson has no support for date/datetime verification, at least that I could find in their repo.

### Steps to reproduce

1. Make a 1.1 manifest with a `ReleaseDate` field (singleton and installer types both have the field, so you have options).
2. Put something that is not a ISO 8601 (YYYY-MM-DD) date in there.
3. Run `winget validate <path to manifest folder>`.

Here is an example:
```
# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.1.0.schema.json
PackageIdentifier: Microsoft.VisualStudio.2022.BuildTools
PackageVersion: 17.0.1
PackageName: Visual Studio Build Tools 2022 Current
Publisher: Microsoft
License: Copyright (c) Microsoft Corporation. All rights reserved.
LicenseUrl: https://visualstudio.microsoft.com/license-terms/
Tags:
- C++
- tools
- C#
- build
- vs
Moniker: vs2022-buildtools
ReleaseDate: "Uh, last Tuesday I think?"
ShortDescription: These Build Tools allow you to build Visual Studio projects from a command-line interface. Use of this tool requires a valid Visual Studio license.
PackageUrl: https://visualstudio.microsoft.com/
Installers:
- Architecture: x64
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/8cea3871-c742-43fb-bf8b-8da0699ab4af/25c54d66f5cf07b14cdc0d6dab2e3d5da7ec22dead4757e69011bb2b2946e384/vs_BuildTools.exe
  InstallerSha256: 25C54D66F5CF07B14CDC0D6DAB2E3D5DA7EC22DEAD4757E69011BB2B2946E384
  InstallerType: exe
  InstallerSwitches:
    Silent: --quiet
    SilentWithProgress: --passive
    Custom: --wait
    Upgrade: update
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.1.0
```

### Expected behavior

```
Manifest validation failed.

ReleaseDate field must be a ISO 8601 (YYYY-MM-DD) date. 

```

### Actual behavior

`Manifest validation succeeded`.

### Environment

```shell
Windows Package Manager v1.1.12986 (also verified on current dev build)
Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.16.12986.0

Any additional software? I have installed Rover the Dog from Windows XP to search through my files, although I don't know what his opinion is on ISO 8601 dates.
```
