### ISSUE TITLE
Manifest Field for User Manual / Documentation

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#1984]
### Description of the new feature / enhancement

As a user, there are times where I would like to quickly view the documentation related to a specific application. This is sometimes different than the support URL, as some publishers make their software manuals or guides available online.

### Proposed technical implementation details

Add an optional field to the Locale manifest - `DocumentationUrls`

```yaml
DocumenationUrls:
- DocumentDescription: Installation Guide
  DocumentUrl: https://github.com/microsoft/winget-cli#installing-the-client
- DocumentDescription: Settings Guide
  DocumentUrl: https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md
- DocumentDescription: Troubleshooting
  DocumentUrl: https://github.com/microsoft/winget-cli/blob/master/doc/troubleshooting/README.md
```
