### ISSUE TITLE
Additional AppsAndFeaturesEntry fields for ARP Matching

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#2183]
### Description of the new feature / enhancement

In the AppsAndFeaturesEntry, there are additional fields which could be used for ARP Matching if they were added to the manifest and were populated by package maintainers. Any available ARP fields could be added to the manifest to improve ARP Matching

### Proposed technical implementation details

```yaml
AppsAndFeaturesEntries:
  - DisplayName: # This already exists
    Publisher: # This already exists
    DisplayVersion: # This already exists
    ProductCode: # This already exists
    UpgradeCode: # This already exists
    InstallerType: # This already exists
    HelpLink: # This is new
    UrlInfoAbout: # This is new
    URLUpdateInfo: # This is new
    EstimatedSize: # This is new
```
