### ISSUE TITLE
Track "primary" AppsAndFeaturesEntry for better matching

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-cli#2186]
### Description of the new feature / enhancement

During the review for https://github.com/microsoft/winget-cli/pull/2137, @JohnMcPMS brought up the good point that winget currently doesn't have a way to know which uninstaller to run if a package creates multiple ARP entries. Most applications will have a certain ARP entry that runs an uninstaller that will remove everything the app installed, so that you don't have to go through the list and manually remove them one by one. This value also often is the one that we should probably use for tracking the "true" version number of the package, since it's typically the ARP entry for the main component of the app.

We need a way to tell winget which ARP entry to treat as the main one.

### Proposed technical implementation details

There should be an addition to the AppsAndFeaturesEntries portion of the schema that allows the manifest author to denote a single ARP entry as the primary one, so winget knows which uninstaller to run (and when an upgrade is necessary).

```
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Maintenance Service
    DisplayVersion: 99.0.1
    Publisher: Mozilla
    ProductCode: MozillaMaintenanceService
  - DisplayName: Mozilla Firefox (x86 nb-NO)
    DisplayVersion: 99.0.1
    Publisher: Mozilla
    ProductCode: Mozilla Firefox 99.0.1 (x86 nb-NO)
    Primary: true
    ```
