### ISSUE TITLE
Shows very old version in its search for Vivaldi browser

### ISSUE THREAD

**Issue by GwenDragon** [microsoft/winget-cli#2681]
### Brief description of your issue

When you start with winget a search for _vivaldi_ you will get a very old outdated version 5.2 browser. 

### Steps to reproduce

2. Run `winget search vivaldi`
3. You will see this (sorry, could not switch Windows to english lang):
```
`T:\>winget search vivaldi
Name             ID                                   Version     Übereinstimmung  Quelle
-----------------------------------------------------------------------------------------
Vivaldi          VivaldiTechnologies.Vivaldi          5.2.2623.39                  winget
Vivaldi Snapshot VivaldiTechnologies.Vivaldi.Snapshot 5.2.2617.2  Command: vivaldi winget

T:\>winget show vivaldi
Gefunden Vivaldi [VivaldiTechnologies.Vivaldi]
Version: 5.2.2623.39
Herausgeber: Vivaldi Technologies AS.
Herausgeber-URL: https://vivaldi.com
Herausgeber-Support-URL: https://help.vivaldi.com
Autor: Vivaldi Technologies AS.
Moniker: vivaldi
Beschreibung: The new Vivaldi browser protects you from trackers, blocks unwanted ads, and puts you in control with unique built-in features. Get Vivaldi and browse fast.
Startseite: https://vivaldi.com/features
Lizenz: Proprietary freeware
Lizenz-URL: https://vivaldi.com/privacy/vivaldi-end-user-license-agreement
Datenschutz-URL: https://vivaldi.com/privacy/browser
Copyright: © Vivaldi Technologies All rights reserved.
Copyright-URL: https://vivaldi.com/privacy/vivaldi-end-user-license-agreement
Installationsprogramm:
  Typ: exe
  Download-URL: https://downloads.vivaldi.com/stable-auto/Vivaldi.5.2.2623.39.x64.exe
  SHA256: 568ae7f591e65f935189628f0d32564655988e55f9a3bfa2a12baec66d143379
  Freigabedatum: 2022-04-16

```

### Expected behavior

Current Vivaldi versions are shown

### Actual behavior

Outdated Vivaldi version numbers for 5.2 are shown

### Environment

```shell
T:\>winget --info
Windows-Paket-Manager v1.3.2691
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19045.2193
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.18.2691.0
```
