### ISSUE TITLE
An unexpected error occurred while executing the command: 0x80070032 : The request is not supported.

### ISSUE THREAD

**Issue by retnikt** [microsoft/winget-cli#290]
# Brief description of your issue

When I try to install from a manifest I get this error message.

I am trying to create a manifest for the Google Cloud SDK. I created the YAML file using the YAMLCreate.ps1. The manifest 

I don't know if this is a bug, or if there's something wrong with my manifest file, in which case there should be a more descriptive error message.

# Steps to reproduce

Use this manifest file:
```yaml
Id: Google.CloudSDK
Version: 293.0.0
Name: CloudSDK
Publisher: Google
License: Apache License v. 2.0
AppMoniker: gcloud
Tags: google, cloud, sdk, google-cloud-platform, python, gcp, platform
Description: Tools and libraries for interacting with Google Cloud products and services
Homepage: https://cloud.google.com/sdk/
Installers:
  - Arch: x64
    Url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-293.0.0-windows-x86_64.zip
    Sha256: 3F2F2DB80FD2359BE44895D1945C315F2CF7F0F722E00C20F7D71EFE9C3965E5
    InstallerType: zip
```
And run:
```none
PS C:\> winget validate .\293.0.0.yaml
Manifest validation succeeded
PS C:\ winget install --manifest .\293.0.0.yaml
Found CloudSDK [Google.CloudSDK]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
An unexpected error occurred while executing the command:
0x80070032 : The request is not supported.
```

# Expected behavior

Either the installation succeeds, or fails with a more useful error message.

# Actual behavior

Completely unhelpful error message:
```
Found CloudSDK [Google.CloudSDK]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
An unexpected error occurred while executing the command:
0x80070032 : The request is not supported.
```

# Environment

```none
Windows Package Manager v0.1.41331 Preview
Windows: Windows.Desktop v10.0.19041.84
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```
Any other software?
[YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/538b79a/Tools/YamlCreate.ps1)
