### ISSUE TITLE
Winget not respecting -l option

### ISSUE THREAD

**Issue by Devang-Solanki** [microsoft/winget-cli#3140]
### Brief description of your issue

The Windows package manager 'winget' provides an option "-l" which allows the user to specify a custom installation directory for the application being installed. However, it has been observed that this option does not work with popular applications like VMware Player, Virtual Box, Android Studio etc despite their installers supporting changing the installation location. This issue can cause inconvenience to users who prefer to install their applications in non-default locations.

### Steps to reproduce

- Type `winget install Google.AndroidStudio -l D:\Custom\Path`

### Expected behavior

Android studio should install at `D:\Custom\Path`

### Actual behavior

It's getting install at default location.

### Environment

```shell
Windows: Windows.Desktop v10.0.22621.1413
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by Trenly** [comment]
Duplicate of #2812

**Comment by Trenly** [comment]
The location switch will need to be added to the manifests, if the installers support it as you say they do. Each will need to be updated at [winget-pkgs](/microsoft/winget-pkgs). I'll take a look at them and open issues for the ones without location switches

**Comment by Trenly** [comment]
VirtualBox has an install location parameter already defined -
```
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --msiparams "INSTALLDIR="<INSTALLPATH>""
  Custom: -msiparams REBOOT=ReallySuppress
```

I've opened issues for the other two mentioned
