### ISSUE TITLE
Unalbe t

### ISSUE THREAD

**Issue by OreoFrosting** [microsoft/winget-cli#3368]
### Brief description of your issue

When I run winget configure on my yaml file, I get the message "The module for the configuration unit is available in multiple locations within the same version." I've also had trouble finding the correct resource name within given DSC modules, is there an easy way to do this that I am unaware of? I think I'm using the correct resource to get vscode and 7zip. 

```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: WinGetPackage
      id: vsCode
      directives:
        module: Microsoft.WinGet.DSC
        description: 'Install Microsoft Visual Studio Code'
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: 7zip
      directives:
        description: Install 7Zip
        allowPrerelease: true
      settings:
        id: 7zip.7zip
        source: winget
  configurationVersion: 0.2.0
```

![wingetError](https://github.com/microsoft/winget-cli/assets/16746224/99241dd0-62e3-4fb4-a100-cd7a621b220a)

### Steps to reproduce

Run winget configure with my given yaml code

### Expected behavior

I expected both vscode and 7zip to install as expected

### Actual behavior

An error/warning is given 

### Environment

```shell
Windows Package Manager (Preview) v1.6.1573-preview
Windows: Windows.Desktop v10.0.19044.1348
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.1573.0
```
