### ISSUE TITLE
[Feature Request] Area Download URL

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/winget-cli#3407]
### Description of the new feature / enhancement

Some developers or publishers of software may upload links on different platforms, and these links may download quickly in some regions, but very slowly in others
I would like to have an option to automatically switch to the link in the specified area to download, which will improve the download speed

> PS: Users can choose URLs whatever they want

### Proposed technical implementation details

```yaml
Installers:
- Architecture: x86
  Area: China
  InstallerUrl: xxx
  InstallerSha256: xxx
- Architecture: x86
  Area: US
  InstallerUrl: xxx
  InstallerSha256: xxx
- Architecture: x86
  Area: Global
  InstallerUrl: xxx
  InstallerSha256: xxx
```
