### ISSUE TITLE
Make InstallationNotes flow-dependent

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#3483]
### Description of the new feature / enhancement

Allow different messages to be shown on Install, Upgrade, and Uninstall.

### Proposed technical implementation details

To keep manifests clean, I would prefer the field be changed to an object rather than adding new manifests fields, although I suppose either would work. With the 2020-12 schema, it might also be possible to allow for backwards compatibility to prevent this from being a breaking change.

```yaml
InstallationNotes:
	- Install:
    	- Before: This message is shown before a package is installed
    	- After: This message is shown after a package is installed
	- Upgrade:
    	- Before: This message is shown before a package is upgraded
    	- After: This message is shown after a package is upgraded
	- Uninstall:
    	- Before: This message is shown before a package is uninstalled
    	- After: This message is shown after a package is uninstalled
```
