### ISSUE TITLE
Install4J installer support

### ISSUE THREAD

**Issue by Restia666Ashdoll** [microsoft/winget-cli#360]
# Description of the new feature/enhancement
Support for Install4J installer, so that we can use apps like BiglyBT
https://www.ej-technologies.com/products/install4j/overview.html

# Proposed technical implementation details (optional)
```
Id: biglysoftware.biglybt
Version: 6.9.1
Name: BiglyBT
Publisher: BiglySoftware
License: GNU General Public License v2.0
LicenseUrl: https://github.com/BiglySoftware/BiglyBT/blob/master/LICENSE
AppMoniker: biglybt
Tags: BitTorrent client
Description:
  Feature-filled Bittorrent client based on the Azureus open source project
Homepage: https://www.biglybt.com/
InstallerType: Install4J
Installers:
  - Arch: x64
    Url: https://github.com/BiglySoftware/BiglyBT/releases/download/v2.4.0.0/Github_BiglyBT_Installer64.exe
    Sha256: 60f2c8cb74deaded9d31656c353163b574b9a7114e1cdea9143a454eb7b1dbc3

```
Install4J uses `-q` for silent installation.

**Comment by wjk** [comment]
You don’t need any special support in winget itself for this use-case. You can simply specify the install type as EXE and pass the `-q` flag in the Switches/Silent field in the YAML manifest.

**Comment by denelon** [comment]
We can look at metadata associated with Install4J to see if there are attributes the winget.exe client can take advantage of.

**Comment by noyard** [comment]
See https://www.ej-technologies.com/resources/install4j/help/doc/installers/options.html

to pass parameters you can use 
"-varfile <filename> "  to pass a file with the parameters 
or 
"-VvariableName=value" to pass individual parameters (there are no limits on how many variables you can pass with this parameter). 

I put in a request for a varfile to be a URL, and it may be included in the next release (version 12).

**Comment by SpecterShell** [comment]
> See [ej-technologies.com/resources/install4j/help/doc/installers/options.html](https://www.ej-technologies.com/resources/install4j/help/doc/installers/options.html)
> 
> to pass parameters you can use "-varfile " to pass a file with the parameters or "-VvariableName=value" to pass individual parameters (there are no limits on how many variables you can pass with this parameter).
> 
> I put in a request for a varfile to be a URL, and it may be included in the next release (version 12).

The varfile is unnecessary. install4j installers already have sufficient parameters for use in WinGet. Here are some examples: https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs%20%22%23%20install4j%22&type=code

My installer switches set for install4j installers is as follows:
```yaml
InstallerSwitches:
  Silent: -q -Dinstall4j.suppressUnattendedReboot=true
  SilentWithProgress: -q -splash "" -Dinstall4j.suppressUnattendedReboot=true
  InstallLocation: -dir "<INSTALLPATH>"
  Log: -Dinstall4j.log="<LOGPATH>"
```

**Comment by denelon** [comment]
**Issue summary**
- Request: dedicated support for Install4J installers (e.g., BiglyBT).

**Disposition**
- Install4J installers are fully supported today with the existing `exe` installer type plus `InstallerSwitches` — no dedicated installer type is needed. As shown by @SpecterShell, a working switch set is:

```yaml
InstallerSwitches:
  Silent: -q -Dinstall4j.suppressUnattendedReboot=true
  SilentWithProgress: -q -splash "" -Dinstall4j.suppressUnattendedReboot=true
  InstallLocation: -dir "<INSTALLPATH>"
  Log: -Dinstall4j.log="<LOGPATH>"
```

- Many packages in winget-pkgs already ship Install4J apps this way ([`# install4j` code search](https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs+%22%23+install4j%22&type=code)).
- Since the scenario works with existing functionality, closing this out. Thanks @SpecterShell for documenting the pattern.

*Drafted with the help of GitHub Copilot.*
