### ISSUE TITLE
WinGet configuration fails on some msstore packages

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#3728]
We've isolated the issue with this one. It's a bug.
The workaround is to put the value for the "id:" in quotes.

```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/PowerShell/PowerShell/blob/master/docs/building/windows-core.md
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: WindowsTerminal
      directives:
        description: Install Windows Terminal
        allowPrerelease: true
      settings:
        id: "9N0DX20HK701"
        source: msstore
  configurationVersion: 0.2.0
```

_Originally posted by @denelon in https://github.com/microsoft/winget-cli/issues/3705#issuecomment-1745196138_
