### ISSUE TITLE
Winget configuration "PSDscResources/Script" error when running "code --install-extension" 

### ISSUE THREAD

**Issue by PShipstone** [microsoft/winget-cli#3887]
### Brief description of your issue

When using `Winget configuration`,  a `PSDscResources/Script` resource generates an error when running `code --install-extension` when the extension is not installed.   Even though the warning is generated, the vscode extensions do get installed.

### Steps to reproduce

1. Ensure the required VSCode extensions are uninstalled.

2. Create a YAML DSC file, for example:

```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:      
    - resource: PSDscResources/Script
      id: myAppConfig
      directives:
        description: Configure My App
        allowPrerelease: true
      settings:
        GetScript: |
          # Your custom PowerShell code to check app configuration
        TestScript: |
          return $false
        SetScript: |
          # PowerShell script commands to install VSCode extensions
          code --install-extension jebbs.plantuml 
          code --install-extension yzhang.markdown-all-in-one      
  configurationVersion: 0.2.0 
```
3. Execute WinGet, for example:  

```
winget configuration C:\tmp\dev-machine.dsc.yaml
```

### Expected behavior

The VSCode extentions get installed with no warnings

### Actual behavior

The following error is generated 

![image](https://github.com/microsoft/winget-cli/assets/44038179/54d213aa-61fc-4d78-b982-5a33012bc5d6)

### Environment

```shell
Windows Package Manager (Preview) v1.7.2782-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2506
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.2782.0
```

**Comment by denelon** [comment]
I attempted to get a "clean" reproduction using Windows Sandbox. I got this error when running the configuration from a clean state without Visual Studio Code being installed. It looks like the environment variable for the path to "code.exe" hasn't been applied before running the script resource.

<img width="674" alt="3887" src="https://github.com/microsoft/winget-cli/assets/61799811/a105f49d-1369-4ef4-b653-4543ee7318c7">

If I close and reopen PowerShell and run the same configuration again (with Visual Studio Code now in the path), I do get the error you reported from the image above.

I put all 3 attached files (you'll need to unzip them) in my "C:\Sandbox" directory and then ran `winget configure C:\Sandbox\sandbox.dsc.yaml`.

Note: You may need to unblock one or more of the files due to the Mark of the Web being applied.

@SteveL-MSFT do you have any ideas on this exception?


[3887.dsc.zip](https://github.com/microsoft/winget-cli/files/13351751/3887.dsc.zip)

**Comment by denelon** [comment]
It looks like that is actually coming from VSCode or the extension itself, and not related to the Script resource.

<img width="489" alt="3887-2" src="https://github.com/microsoft/winget-cli/assets/61799811/ce017e39-7a48-40c2-a042-078b115a28ab">

**Comment by denelon** [comment]
Running $LASTEXITCODE returns a 0, so that's just a warning.

**Comment by denelon** [comment]
I updated the configuration to refresh the environment variables for path, and got it to work on the first run without VSCode installed.

```YAML
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

###############################################################################
# Attempting to reproduce https://github.com/microsoft/winget-cli/3887        #
############################################################################### 

properties:
  resources:      
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VSCode
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: PSDscResources/Script
      dependsOn: 
        - VSCode
      id: myAppConfig
      directives:
        description: Configure My App
        allowPrerelease: true
      settings:
        GetScript: |
          # Your custom PowerShell code to check app configuration
        TestScript: |
          return $false
        SetScript: |
          # PowerShell script commands to install VSCode extensions
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          code --install-extension jebbs.plantuml 
          code --install-extension yzhang.markdown-all-in-one      
  configurationVersion: 0.2.0 
```
