### ISSUE TITLE
winget configure failing remote

### ISSUE THREAD

**Issue by Pearmint** [microsoft/winget-cli#3901]
### Brief description of your issue

When executing `winget configure -f configure.dsc.yml --accept-configuration-agreements` remotely over WinRM/PSRP the command will fail.

If executed local the command succeeds.

### Steps to reproduce

1. Create configure.dsc.yml 
```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: 7zip
      directives:
        description: Install 7-Zip
        allowPrerelease: true
      settings:
        id: "7zip.7zip"
        source: winget
  configurationVersion: 0.2.0
```

2. Execute `winget configure -f configure.dsc.yml --accept-configuration-agreements` via WinRM or PSRP.

### Expected behavior

Testing the configuration status on the machine and then installing missing software via the Microsoft.WinGet.DSC package.

### Actual behavior

The testing of the current system state fails with the message: _Failed to create instance: -2147023174_.

### Environment

```shell
Windows-Paket-Manager v1.6.3133
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22621.2715
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.3133.0
```
