### ISSUE TITLE
Failure to install Visual Studio workloads with VSComponents step

### ISSUE THREAD

**Issue by flowcoder1** [microsoft/winget-cli#3914]
### Brief description of your issue

Cannot install Visual Studio 2022 Community workloads using the Microsoft.VisualStudio.DSC/VSComponents resource, either via winget configure or DevHome. Tested on two machines plus Windows Sandbox.

Fails with:
```
Apply :: VSComponents
  The configuration unit was not in the module as expected.
```

Tried installing the modules separately with `Install-Module -Name Microsoft.VisualStudio.DSC -AllowPrerelease` but it didn't help.

### Steps to reproduce

Using the following configuration file with `winget configure .\configuration.dsc.yaml --verbose-logs` :

```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/microsoft/terminal#prerequisites
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      id: DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 (any edition is OK)
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Community
        source: winget
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      dependsOn:
        - vsPackage
      directives:
        description: Install required VS workloads
        allowPrerelease: true
      settings:
        productId: Microsoft.VisualStudio.Product.Community
        channelId: VisualStudio.17.Release        
        components:
          - Microsoft.VisualStudio.Workload.ManagedDesktop
          - Microsoft.VisualStudio.Workload.Universal
  configurationVersion: 0.2.0
```

This results in:
```
Assert :: OsVersion
  Configuration successfully applied.
Apply :: DeveloperMode [DeveloperMode]
  Configuration successfully applied.
Apply :: WinGetPackage [vsPackage]
  Configuration successfully applied.
Apply :: VSComponents
  The configuration unit was not in the module as expected.
Some of the configuration was not applied successfully.
```

### Expected behavior

Visual Studio to install the required components. It also doesn't work with specifying a `.vsconfig` file.

### Actual behavior

The Visual Studio installer installs, but none of the components install.

### Environment

```shell
Windows Package Manager v1.6.3133
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1702
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```
