### ISSUE TITLE
Recommended Packages

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#3928]
### Description of the new feature / enhancement

Some packages have related software to make them work better or provide additional functionality. It would be nice if a user were informed of these related packages after install.

For example, Audacity can have additional codecs enabled by installing a specific FFMPEG package. After install, a user may be interested in also installing that package.

Additionally, when Verified Publishers are complete, they may want to promote their other related software.

### Proposed technical implementation details

Manifest -
```yaml
ReccomendedPackages:
- PackageIdentifier: Example.PackagePlus
  RecommendationReason: This package adds the ability to abc123 in Package.Example
- PackageIdentifier: Example.PackageMinus
```

Output -
```raw
Installation Complete!

You may be interested in these related packages:
  Example.PackagePlus - This package adds the ability to abc123 in Package.Example
  Example.PackageMinus
```

Also could be a user setting to suppress recommended packages
