### ISSUE TITLE
winget doesn't automatically understand machine-scope MSI installers

### ISSUE THREAD

**Issue by jantari** [microsoft/winget-cli#3969]
### Description of the new feature / enhancement

When a winget manifest contains both a user and a machine scope installer definition, both MSIs, winget-cli on the client side doesn't automatically handle the machine-scope case for MSIs (aka appending `ALLUSERS=1` on the commandline).

winget-cli should automatically understand machine-scope MSI installs wihtout the package-maintainers having to manually define installer switches. This already works for user-scope MSI (appending `/qb`, `/qn` etc., and wix, inno installers etc.).

### Proposed technical implementation details

Given an installer manifest exceprt like this:

```yaml
Installers:
- Architecture: x64
  InstallerType: msi
  Scope: user
  InstallerUrl: https://github.com/pdfarranger/pdfarranger/releases/download/1.10.0/pdfarranger-1.10.0-windows-installer.msi
  InstallerSha256: B77A5DC7C956F1E0986664B0587B9B7532CA304590F4F1C86B03960486DDE4F6
- Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://github.com/pdfarranger/pdfarranger/releases/download/1.10.0/pdfarranger-1.10.0-windows-installer.msi
  InstallerSha256: B77A5DC7C956F1E0986664B0587B9B7532CA304590F4F1C86B03960486DDE4F6
```

which is an edited version of https://github.com/microsoft/winget-pkgs/blob/master/manifests/p/PDFArranger/PDFArranger/1.10.0/PDFArranger.PDFArranger.installer.yaml to add support for machine-scope installs, winget-cli should install the MSI properly for all users because "Scope: machine" was defined in the manifest.

Currently, this is not the case. winget-cli does not append the correct parameter (`ALLUSERS=1`) and the machine-scope installer ends up being installed per-user anyway, despite `winget install --scope machine`.

A workaround I tested is to manually specify the `ALLUSERS=1` switch. This works:

```yaml
Installers:
- Architecture: x64
  InstallerType: msi
  Scope: user
  InstallerUrl: https://github.com/pdfarranger/pdfarranger/releases/download/1.10.0/pdfarranger-1.10.0-windows-installer.msi
  InstallerSha256: B77A5DC7C956F1E0986664B0587B9B7532CA304590F4F1C86B03960486DDE4F6
- Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://github.com/pdfarranger/pdfarranger/releases/download/1.10.0/pdfarranger-1.10.0-windows-installer.msi
  InstallerSha256: B77A5DC7C956F1E0986664B0587B9B7532CA304590F4F1C86B03960486DDE4F6
  InstallerSwitches:
    Custom: ALLUSERS=1
```

However I believe the built-in convenience of winget to automatically know the right parameters for many setup types, including per-user MSI, should be expanded to automatically support per-machine MSI as well so this workaround is no longer needed.
