### ISSUE TITLE
winget configure with Registry resource unable to write to HKLM:\SOFTWARE\### from admin shell

### ISSUE THREAD

**Issue by sperry** [microsoft/winget-cli#3996]
### Brief description of your issue

Running from an administrator "cmd" prompt I am trying to use "winget configure" to apply the following:

```
properties:
  resources:
    - resource: Registry
      directives:
        description: add
      settings:
        Key: 'HKLM:\SOFTWARE\XYZ'
        Ensure: 'Present'
        ValueName: ''
        ValueType: 'String'
        ValueData: ''
        Force: 1
  configurationVersion: 0.2.0
```
I get 

> Apply :: Registry
>   The configuration unit failed while attempting to apply the desired state.
> Exception calling "OpenSubKey" with "2" argument(s): "Requested registry access is not allowed."
> <See the log file for additional details>
> 

It's only an issue creating Key directly under SOFTWARE.  Again I am running from Administrator shell.  Is Winget running as some other user

### Steps to reproduce

- Open cmd shell as Administrator
- winget configure -f <file containing above config>

### Expected behavior

Registry key should be created as expected since I'm Administrator

### Actual behavior

Registry key not created and error says "Requested registry access is not allowed"

### Environment

```shell
Windows Package Manager (Preview) v1.7.2491-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.2491.0
```
