### ISSUE TITLE
"Add installation path to PATH env" function

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-cli#4008]
### Description of the new feature / enhancement

There is some software that install cli version's but do not modify PATH env, it's not realistic to expect that every installer will be updated to modify, therefore having such function in winget will be nice.

Example packages that have cli version's but don't add installation path to PATH env so you can't use them out of the box:
[proxinject](https://github.com/PragmaTwice/proxinject/issues/13)
[7-Zip-zstd](https://github.com/mcmilk/7-Zip-zstd/issues/360)
7zip
this issue have many more example of such software https://github.com/microsoft/winget-cli/issues/549

### Proposed technical implementation details

Example for proxinject package:
```
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/PragmaTwice/proxinject/releases/download/v0.5.0-pre/proxinjectSetup-v0.5.0-pre-x64.exe
  InstallerSha256: 9F8D33D6FEAE2D3042D01F129204318885178A9363EA9AAF468FABE9F4E2F9E2
  AddToPath: $env:APPDATA\proxinject | <INSTALLPATH>
```

AddToPath should only work in Silent or SilentWithProgress modes as user can modify installation path in interactive mode and winget will add wrong path to env.

If user is not specified `--location` argument it will use default value `$env:APPDATA\proxinject` otherwise it will add `<INSTALLPATH>` to `PATH`
