### ISSUE TITLE
Add Support for ZIP for Installer Type

### ISSUE THREAD

**Issue by crpietschmann** [microsoft/winget-cli#412]
# Description of the new feature/enhancement

It would be a great addition if a ZIP could be used for installing something in addition to the supported exe/msi/etc options. This would allow applications that don't have an installer package to be able to be installed and managed using `winget`.

One example would be Terraform. It's downloaded as a .zip that contains an exe that needs to be placed on the machine somewhere, then the terraform.exe needs to be added to the system PATH so users can use it from the command-line. It contains no installer so script support in `winget` packages would allow this to be easily and quickly installed using `winget`.

# Proposed technical implementation details (optional)

A new `InstallerType: zip` could be added that supports installing things contained within a zip file. The `zip` file would be downloaded similarly to how exe/msi/etc are today, then unpacked into a destination folder. Also, it would need a flag such as `AddPATH: true` to add the destination folder to the system path so any exe's contained within the folder could be used at the command-line.

Here's an example:

```
InstallerType: zip
Installers:
  - Arch: x64
    Url: https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_windows_amd64.zip
    Sha256: XXXXXXXXXXXSHA256HASHXXXXXXXXXXXX
    AddPATH: true
```
