### ISSUE TITLE
Repair-WinGetPackageManager failing due to dependencies

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#4228]
### Brief description of your issue

When I run Repair-WinGetPackageManager in the Windows Sandbox it's failing to complete.

### Steps to reproduce

Run the following as a configuration to configure and start Windows Sandbox.
>Note: The Windows Sandbox feature must be enabled.

```YAML
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

###############################################################################
# Create Windows Sandbox instance with WinGet installed.                      #
# Run as Administrator                                                        #
# Mount C:\Sandbox on the local filesystem into the Sandbox filesystem.       #
# The Logon command performs the following steps in Windows PowerShell:       #
# 1. Install Nuget package provider                                           #
# 2. Install Microsoft.WinGet.Client (0.2.1) PS module from the PS gallery.   #
# 3. Set the execution policy to RemoteSigned                                 #
# 4. Run Repair-WingetPackageManager to install App Installer (WinGet).       #
# Note: Modifying the C:\Sandbox directory contents in Windows Sanbox         #
#       will also modify C:\Sandbox on the Host filesystem.                   #
############################################################################### 

properties:
  resources:
    - resource: Microsoft.WindowsSandbox.DSC/WindowsSandbox
      directives:
        description: Create Windows Sandbox with Winget installed
        allowPrerelease: true
      settings:
        Ensure: Present        
        HostFolder: C:\Sandbox
        SandboxFolder: C:\Sandbox
        LogonCommand: >
          cmd /c start powershell -NoExit -Command "Write-Host 'Installing NuGet package provider...';
          Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force;
          Write-Host `n'Installing Microsoft.WinGet.Client PowerShell module...' `n;
          Install-Module Microsoft.WinGet.Client -Repository PSGallery -Force;
          Write-Host 'Setting execution policy to remote signed...' `n;
          Set-ExecutionPolicy RemoteSigned -Force;
          Write-Host 'Running the Repair-WinGetPackageManager cmdlet to install App Installer (WinGet)...' `n;
          Repair-WingetPackageManager;
  configurationVersion: 0.2.0
```

### Expected behavior

The sandbox should launch and WinGet should be configured.

### Actual behavior

Repair-WinGetPackageManager is failing.

### Environment

```shell
Microsoft.WinGet.Client
```
