### ISSUE TITLE
The configuration unit was not in the module as expected

### ISSUE THREAD

**Issue by Gijsreyn** [microsoft/winget-cli#4919]
### Brief description of your issue

When applying the following on a fresh created Hyper-V box through DevHome:

```yaml
#configure.devbox.config.yaml
properties:
  resources:
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    directives:
      description: Installing Git
      allowPrerelease: true
    settings:
      id: "Git.Git"
      source: winget
    id: Git.Git | Git
  - resource: GitDsc/GitClone
    directives:
      description: 'Cloning: winget-dsc.git'
      allowPrerelease: true
      securityContext: current
    settings:
      httpsUrl: https://github.com/microsoft/winget-dsc.git
      rootDirectory: C:\Repos\winget-dsc.git
    id: 'Clone winget-dsc.git: C:\Repos\winget-dsc.git'
    dependsOn:
    - Git.Git | Git
  configurationVersion: 0.2.0
```

I get the error: The configuration unit was not in the module as expected.

Related: https://github.com/microsoft/winget-cli/issues/4021

### Steps to reproduce

Create Hyper-V box through DevHome with default settings. Create a file with the above and execute winget configure configure.devbox.config.yaml --accept-configuration-agreements

### Expected behavior

Clone repository on C:\repos

### Actual behavior

The configuration unit was not in the module as expected.

### Environment

Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.3880
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

**Comment by denelon** [comment]
@Gijsreyn does the same thing happen with WinGet 1.9?

**Comment by janegilring** [comment]
It does happen with WinGet 1.9 in my testing

![Image](https://github.com/user-attachments/assets/4a609e4b-e7cb-4237-9692-6a135fcf0d47)

![Image](https://github.com/user-attachments/assets/bf27a3f7-fb72-442e-9dd5-0a73b11b67ef)

**Comment by Gijsreyn** [comment]
Was about to open up the Hyper-V box, but thanks for checking already @janegilring!

**Comment by ddieppa** [comment]
Same happening to me using **winget**  `v1.9.2411-preview` in
**Windows 11 Version 23H2 (OS build 22631.4391)**

Error:
Apply :: WinGetPackage [Ditto.Ditto]
  The configuration unit was not in the module as expected.

I did run `winget configure validate --file .\apps.dsc.yaml` and `winget configure test --file .\apps.dsc.yaml` and both were succesfull.
this is the file content:
```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/microsoft/winget-create#building-the-client
# WinGet Configure file Generated By Dev Home.

properties:
  configurationVersion: 0.2.0
  resources:
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    directives:
      description: Installing Ditto.Ditto
      allowPrerelease: false
      securityContext: current
    settings:
      id: "Ditto.Ditto"
      source: winget
    id: Ditto.Ditto
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    directives:
      description: Installing Microsoft.PowerToys
      allowPrerelease: false
      securityContext: current
    settings:
      id: "Microsoft.PowerToys"
      source: winget
    id: Microsoft.PowerToys
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    directives:
      description: Installing ShareX.ShareX
      allowPrerelease: false
      securityContext: current
    settings:
      id: "ShareX.ShareX"
      source: winget
    id: ShareX.ShareX
```
