### ISSUE TITLE
[Feat]: Supports optional dependencies

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-cli#5100]
### Description of the new feature / enhancement

There are some packages that run even when there are not have dependencies that are explicitly specified in the manifest.
For example, my package `DuckStudio.GitHubView` can run with `Microsoft.DotNet.Runtime.8` (explicitly specified in the manifest, first choice), and it also can run with other .NET Runtime like `Microsoft.DotNet.Runtime.7` .
I would like winget to assume that the device has the required dependencies when optional dependencies are present in the device, and install the specified program directly instead of installing the other one dependencies.

### Proposed technical implementation details

Optional dependencies can be specified in the manifest by the package author. If an arbitrarily specified dependency does not exist in the device, the first choice dependency is installed. If an arbitrarily specified dependency (first choice or optional) exists in the device, the device is considered to have satisfied the dependency condition.

In the manifest:

```yaml
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.Runtime.8
    optional:
    - Microsoft.DotNet.Runtime.7
```
