### ISSUE TITLE
[Feat]: Support for setting download links for different regions in manifests

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-cli#5138]
### Description of the new feature / enhancement

I've found packages that distribute the exact same installer in two different places, and users in certain areas can't access one of those places. If the manifest only contains the distribution location that they can't access (or have a hard time accessing), then they can't (or have a hard time) getting this package through winget.
For example:
The author of the package `abgox.InputTip` distributes the application on [GitHub](https://github.com/abgox/InputTip/) and [Gitee](https://gitee.com/abgox/InputTip). Users located in China may find it difficult to access GitHub due to policy reasons, which requires winget to choose the distribution link on Gitee instead of GitHub.

### Proposed technical implementation details

I know this can now be fixed using InstallerLocale: zh-CN, but I'm not sure if an installer can set more than one InstallerLocale, and the entry looks more like of an indication of the installer language than a download link.
My personal thoughts on manifests:
```yaml
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: InputTip/InputTip.exe
  InstallerUrl: https://github.com/abgox/InputTip/releases/download/v2.30.2/InputTip.zip
  OtherLacale:
    - Locale: zh
    - InstallerUrl: https://gitee.com/abgox/InputTip/releases/download/v2.30.2/InputTip.zip
  InstallerSha256: 3546A076EFBEDCCC4E6FC6B7C86B13C73B4D7104AE8D1AEFCA6C622CFB79F05C
- Architecture: x64
  InstallerType: portable
  # Note: 新建一个目录，将 InputTip.exe 放入其中，然后再运行它 (https://inputtip.pages.dev/download/)
  InstallerUrl: https://github.com/abgox/InputTip/releases/download/v2.30.2/InputTip.exe
  OtherLacale:
    - Locale: zh
    - InstallerUrl: https://gitee.com/abgox/InputTip/releases/download/v2.30.2/InputTip.exe
  InstallerSha256: D0F118653EE147521CEBFA5D3C7DC8198EB371B1A766112C57F382478CC14994
# zh -> zh-CN, zh-TW, zh-HK... -> Or China
# Multiple regions separated by , ?
```
