### ISSUE TITLE
WinGet configure command on WS 2025 - System.Runtime load error

### ISSUE THREAD

**Issue by mthalman** [microsoft/winget-cli#5260]
### Brief description of your issue

I'm trying to run the `winget configure` command on a Windows Server 2025 machine. It gets an  assembly load error: ` ---> System.Management.Automation.CmdletInvocationException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

### Steps to reproduce

Using a fresh installation of Windows Server 2025:

1. Run `winget configure -f "C:\Users\mthalman\Desktop\dotnet_basic_config_website.winget" --accept-configuration-agreements`

`dotnet_basic_config_website.winget`:
```
# This configuration file installs the .NET 9 SDK, VS Code, and C# Dev Kit on the .NET website.
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: install-dotnet9-SDK
      directives:
        description: Install .NET 9 SDK
      settings:
        id: Microsoft.DotNet.SDK.9
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: install-vs-code
      directives:
        description: Install Visual Studio Code
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.VSCode.DSC/VSCodeExtension
      id: install-csharp-dev-kit
      dependsOn:
        - install-vs-code
      directives:
        description: Install C# Dev Kit
        allowPrerelease: true
      settings:
        name: ms-dotnettools.csdevkit
        exist: true
  configurationVersion: 0.2.0
```

### Expected behavior

Install succeeded

### Actual behavior

[WinGet-2025-02-28-20-43-30.058.log](https://github.com/user-attachments/files/19033068/WinGet-2025-02-28-20-43-30.058.log)

### Environment

```shell
Windows Package Manager v1.6.10121
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Server v10.0.26100.3194
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.10121.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```
