### ISSUE TITLE
`securityContext: elevated` does not have an effect with the PowerShell module

### ISSUE THREAD

**Issue by mdanish-kh** [microsoft/winget-cli#5369]
### Brief description of your issue

When using `Invoke-WinGetConfiguration` in `Microsoft.WinGet.Configuration` PowerShell module, the execution does not ask for elevation when `securityContext: elevated` is present in the configuration. Any module that requires elevation thus fails if the session is not run in elevated permissions manually

### Steps to reproduce

1. Install [Microsoft.WinGet.Configuration](https://www.powershellgallery.com/packages/Microsoft.WinGet.Configuration) PowerShell module
2. Test against a `configuration.winget` file like

```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        # Only requires elevation for the set operation. To reproduce the issue
        # make sure developer mode is currently disabled
        securityContext: elevated
        allowPrerelease: true
      settings:
        Ensure: Present
  configurationVersion: 0.2.0
```

Microsoft.Windows.Developer/DeveloperMode requires elevation only for SET, so to reproduce make sure developer mode is currently disabled

3.  Run `Get-WinGetConfiguration -File configuration.winget | Invoke-WinGetConfiguration`

### Expected behavior

Configuration asks for UAC, applies desired state and returns with a success code

### Actual behavior

Does not ask with UAC and since the config requires admin, it fails with an error code. If I elevate manually with `sudo`, the configuration applies the desired state successfully

![Image](https://github.com/user-attachments/assets/f8098771-0d09-49a6-ac5f-c273ac2b4fa7)

### Environment

```shell
~ Get-Module Microsoft.WinGet.Configuration | Select Version

Version
-------
1.10.340
```

**Comment by mdanish-kh** [comment]
For convenience, one can also test with a resource that requires elevation both for GET and SET, such as:

```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: PSDscResources/WindowsOptionalFeature
      directives:
        description: Install VirtualMachinePlatform
        securityContext: elevated
      settings:
        name: VirtualMachinePlatform
        ensure: Present
  configurationVersion: 0.2.0
```

But that seems to have its own issues sometimes with DISM APIs not working (https://github.com/microsoft/winget-cli/issues/4264). . . I had variable success with this resource sometimes working with Invoke-WinGetConfiguration and sometimes failing
