### ISSUE TITLE
[Feature] Declarative file based configuration for e.g. automation

### ISSUE THREAD

**Issue by Bjego** [microsoft/winget-cli#622]
# Description of the new feature/enhancement

Hey guys, from a dev perspective it would be great, if we could have a declarative, config file based install/uninstall command to install all of our dev teams tools with one command. 
The declarative approach should be able to **install** new applications, **update** existing ones and also to **uninstall** no longer needed programs as well.  

# Proposed technical implementation details (optional)
I could think of a command like :
`bash
winget targetState ./config.yml
`
where config.yml could be:
```yml
- app: Git
  version: x.Y.z
- app: VSCode
  version: c.V.A
- Visual Studio Enterprise
- PowerShell
- Dotnet Core SDK
 
```
