### ISSUE TITLE
The 7z self-extracting package cannot be decompressed

### ISSUE THREAD

**Issue by ystyle** [microsoft/winget-cli#864]
# Brief description of your issue

The 7z self-extracting package cannot be decompressed。 
And tips: there is no such archive

# Steps to reproduce
winget install -m ./kaf-cli.yaml

```yaml
Id: ystyle.kaf-cli
Version: 1.1.11
Name: kaf cli
Publisher: ystyle
Author: ystyle
License: MulanPSL
LicenseUrl: https://github.com/ystyle/TmdTextEpub/raw/master/LICENSE
Description: 把txt文本转成epub和mobi电子书的命令行工具
Homepage: https://github.com/ystyle/TmdTextEpub
Commands: kaf-cli
InstallerType: exe
Installers:
    - Arch: x64
      Url: https://github.com/ystyle/TmdTextEpub/releases/download/v1.1.11/TmdTextEpub-windows.exe
      InstallerType: exe
      Sha256: c278b23d6148ec11538f597b958782185bca2d35090f76e52db812a0a45a9a09
ManifestVersion: 0.1.0

```

# Expected behavior
The 7z self-extracting package is decompressed correctly.

copy the archive to other dir can be decompressed correctly.

# Actual behavior

![](https://dl.ystyle.top/images/2021-04/explorer_2021-04-14_01-22-16.png)
![](https://dl.ystyle.top/images/2021-04/explorer_2021-04-14_01-23-12.png)

# Environment

```none
➜ winget --info
Windows Package Manager v0.2.10771 预览
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.19042.867
程序包: Microsoft.DesktopAppInstaller v1.11.10771.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

链接
-----------------------------------------------
隐私声明   https://aka.ms/winget-privacy
许可协议   https://aka.ms/winget-license
第三方声明 https://aka.ms/winget-3rdPartyNotice
主页       https://aka.ms/winget
```
