### ISSUE TITLE
Default install root

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#970]
# Description of the new feature/enhancement

Some packages are installed based on the location of the installer on the drive. This can be an undesired behavior, and may be further complicated by packages with long paths like Python as discovered in https://github.com/microsoft/winget-pkgs/pull/13076.

# Proposed technical implementation details (optional)

Extend the manifest to support packages that install based on the location of the installer on the device.
Provide a setting for a default install root location. (<path>/<PackageIdentifier>)
Support an argument to specify the install location.
Modify the client to prompt users for an install location when one is required and none is specified in settings.

* https://github.com/microsoft/winget-cli/issues/970
* https://github.com/microsoft/winget-cli-restsource/issues/32
* https://github.com/microsoft/winget-pkgs/issues/13382

**Comment by denelon** [comment]
How about:

```YAML
Installers:
  - InstallerType: exe
    InstallerArchitecture: x64
    InstallerSHA256: 12341234123412341234123412341234123412341234
    InstallerURL: https://www.contoso.com/awesomeapp/1.0.0/awesomeapp.x64.exe
    InstallLocationRequired: boolean
```
