### ISSUE TITLE
Add alternative version number field to manifest to make correlation with entries in Add/Remove programs more reliable

### ISSUE THREAD

**Issue by chausner** [microsoft/winget-cli#980]
# Description of the new feature/enhancement

As reported [here](https://github.com/microsoft/winget-cli/issues/976), the `winget upgrade` command may incorrectly detect updates to be available even when the latest version is installed in case the version number in Add/Remove programs does not match the package version in the manifest.

One solution to this problem could be the addition of an additional version field to the manifest where the version number is specified in the format that is expected in Add/Remove programs. When present, the `winget upgrade` routine would use this version number instead of the package version to determine if an update is available or not.

This suggestion is closely related to microsoft/winget-pkgs#13620.

**Comment by denelon** [comment]
This is part of the work we're doing with the new schema. We have added a section for data specifically matching what is reported via Apps & Features.

**Comment by denelon** [comment]
Related to:
* #1952
* #1073

**Comment by denelon** [comment]
We're going to use this Issue to represent the work to start looking at the version in the AppsAndFeatures section of the manifest (if it is poopulated) rather than the PackageVersion for version comparison.

```YAML
PackageVersion:         # Used for version comparison if no DisplayVersion key is present
- AppsAndFeatures
    DisplayVersion:     # Used for version comparison if the key is present
```
