### ISSUE TITLE
Identify installers that don't work under emulation

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#993]
# Description of the new feature/enhancement

Some installers do not work under emulation. The Windows Package Manager client would try to install these under emulation. There should be a mechanism to identify known architectures where a package shouldn't be installed or wouldn't work correctly.

# Proposed technical implementation details (optional)

**Comment by denelon** [comment]
How about:

```YAML
InstallerArchitecture: x86
UnsupportedOSArchitectures: 
  - ARM64
  - ARM
 ```
